// Turns coverage/coverage-summary.json into docs/quality/coverage.md (reproducible: `npm run test:cov`).
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

type M = { total: number; covered: number; pct: number };
const sum = JSON.parse(readFileSync(join(__dirname, '../coverage/coverage-summary.json'), 'utf8')) as Record<string, { statements: M; branches: M; functions: M; lines: M }>;
const pct = (c: number, t: number) => (t ? Math.round((1000 * c) / t) / 10 : 100);
const dirs = new Map<string, { s: M; b: M; f: M; files: number }>();
const files: { f: string; s: number; b: number; missB: number }[] = [];
for (const [k, v] of Object.entries(sum)) {
  if (k === 'total') continue; const rel = k.split('/src/')[1] ?? k; const d = rel.includes('/') ? rel.slice(0, rel.lastIndexOf('/')) : '(root)';
  const e = dirs.get(d) ?? { s: { total: 0, covered: 0, pct: 0 }, b: { total: 0, covered: 0, pct: 0 }, f: { total: 0, covered: 0, pct: 0 }, files: 0 }; dirs.set(d, e); e.files++;
  for (const [m, x] of [['s', v.statements], ['b', v.branches], ['f', v.functions]] as const) { (e as any)[m].total += x.total; (e as any)[m].covered += x.covered; }
  files.push({ f: rel, s: v.statements.pct, b: v.branches.pct, missB: v.branches.total - v.branches.covered });
}
const t = sum.total;
const out = [
  '# Test coverage', '', `Generated by \`npm run test:cov\` (Istanbul, ts-jest) on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`, '',
  '| Metric | Covered | Total | % |', '|---|---|---|---|',
  ...(['statements', 'branches', 'functions', 'lines'] as const).map((m) => `| ${m} | ${t[m].covered} | ${t[m].total} | ${t[m].pct} |`), '',
  '> **Read lines with care.** Much of the code packs several statements on one line, so *lines* flatters (it is always the highest number). Gate on statements and branches.', '',
  '## By area', '', '| Area | Files | Statements % | Branches % | Functions % |', '|---|---|---|---|---|',
  ...[...dirs].sort((a, b) => pct(a[1].b.covered, a[1].b.total) - pct(b[1].b.covered, b[1].b.total)).map(([d, e]) => `| ${d} | ${e.files} | ${pct(e.s.covered, e.s.total)} | ${pct(e.b.covered, e.b.total)} | ${pct(e.f.covered, e.f.total)} |`), '',
  '## Largest untested branch counts (where the next tests pay off most)', '', '| File | Statements % | Branches % | Uncovered branches |', '|---|---|---|---|',
  ...files.sort((a, b) => b.missB - a.missB).slice(0, 15).map((x) => `| ${x.f} | ${x.s} | ${x.b} | ${x.missB} |`), '',
  '## Files with no automated test at all', '', ...(files.filter((x) => x.s === 0).map((x) => `- \`${x.f}\``).concat([]) || []), '',
  '## What coverage does and does not tell you', '',
  '- It shows code that **never ran** in any test. It does not show that assertions are meaningful: a line can execute without its result being checked. Mutation testing would measure that and has not been run.',
  '- Tests run against a real PostgreSQL (and Redis), so integration paths count; but external systems (AI providers, proctoring vendor, identity provider, Docker sandbox, ClamAV, S3) are exercised only against fakes, so those adapters can show high coverage and still be wrong about the real service.',
  '- `src/main.ts` and `src/worker.ts` are process entrypoints verified by production-mode smoke boots, not by jest.', '',
];
mkdirSync(join(__dirname, '../../docs/quality'), { recursive: true });
writeFileSync(join(__dirname, '../../docs/quality/coverage.md'), out.join('\n'));
console.log('wrote docs/quality/coverage.md');
