// Regenerates docs/api-inventory.json (the reviewed API + access-control contract). Run: npm run inventory
import 'reflect-metadata';
process.env.RATE_LIMIT_DISABLED = '1';
import { Test } from '@nestjs/testing';
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { AppModule } from '../src/app.module';
import { listRoutes } from '../src/platform/inventory';

(async () => {
  const mod = await Test.createTestingModule({ imports: [AppModule] }).compile(); const app = mod.createNestApplication(); await app.init();
  const routes = listRoutes(app).map(({ controller, handler, ...r }) => r);
  writeFileSync(join(__dirname, '../../docs/api-inventory.json'), JSON.stringify({ generatedBy: 'npm run inventory', routes }, null, 1) + '\n');
  // Human-readable reference generated from the same data, grouped by the first path segment after /v1.
  const group = (p: string) => (p.split('/')[2] ?? 'root').replace(/^:.*/, 'root');
  const by = new Map<string, typeof routes>(); for (const r of routes) { const g = group(r.path); by.set(g, [...(by.get(g) ?? []), r]); }
  const md = ['# API reference', '', 'Generated by `npm run inventory` from the live route table; do not edit by hand. "Public" routes need no sign-in (they are protected by signatures, tokens or rate limits instead). Otherwise send `Authorization: Bearer <accessToken>`; a route with roles refuses everyone else with 403, a route without roles accepts any signed-in user.', '', `${routes.length} routes.`, ''];
  for (const [g, rs] of [...by].sort((a, b) => a[0].localeCompare(b[0]))) {
    md.push(`## ${g}`, '', '| Method | Path | Who |', '|---|---|---|');
    for (const r of rs.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))) md.push(`| ${r.method} | \`${r.path}\` | ${r.public ? 'public' : r.roles?.length ? r.roles.join(', ') : 'any signed-in user'} |`);
    md.push('');
  }
  mkdirSync(join(__dirname, '../../docs/guides'), { recursive: true }); writeFileSync(join(__dirname, '../../docs/guides/api-reference.md'), md.join('\n'));
  console.log(`${routes.length} routes written`); await app.close(); process.exit(0);
})();
