// Pure grading rules (ASN-002..005). Everything that decides a score, a deadline penalty, whether a human must look,
// or whether evidence is real lives here, so none of it depends on trusting a model.
import { hasInjection, shingles } from '../ai/quality';

export interface Level { score: number; descriptor: string }
export interface Dimension { id: string; name: string; weight: number; min: number; max: number; levels?: Level[]; evidenceRequired?: boolean; mandatoryModeration?: boolean; disqualifyBelow?: number; testBacked?: boolean }
export interface LateRule { dueAt?: string; graceHours?: number; penaltyPercentPerDay?: number; maxPenaltyPercent?: number; rejectAfterHours?: number }
export type UnlockOn = 'SUBMISSION' | 'AI_SCORE' | 'MODERATED_SCORE' | 'MANUAL';
export interface CodeTests { language: 'python'; entry: string; timeoutMs: number; tests: { name: string; stdin?: string; expectedStdout: string; dimension?: string }[] }
export interface Policy {
  type: string; dimensions: Dimension[]; passPercent: number; confidenceThreshold: number; highStakes: boolean; borderlineMargin: number; samples: number; sampleRate: number;
  prohibitedPatterns: string[]; lateRule: LateRule; unlockOn: UnlockOn; referenceEvidence?: string; discloseAnswerGuide: boolean; minSecondsExpected: number; appealWindowDays: number; codeTests?: CodeTests;
}
export interface PolicyDefaults { confidenceThreshold: number; sampleRate: number; appealWindowDays: number }

export const UNLOCK_VALUES: UnlockOn[] = ['SUBMISSION', 'AI_SCORE', 'MODERATED_SCORE', 'MANUAL'];
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 40) || 'dim';
const GENERIC_LEVELS = ['Missing or incorrect', 'Weak: major gaps', 'Partial: some gaps', 'Good: minor gaps', 'Excellent: complete and accurate'];

/** Fill defaults. An assignment authored before policies existed (or generated by Phase 3) still grades via its rubric criteria. */
export function normalizePolicy(raw: any, rubric: any, d: PolicyDefaults): Policy {
  const r = raw && typeof raw === 'object' ? raw : {};
  let dims: Dimension[] = Array.isArray(r.dimensions) && r.dimensions.length ? r.dimensions : [];
  if (!dims.length && !(Array.isArray(rubric?.criteria) && rubric.criteria.length)) // nothing authored: grade holistically
    dims = [{ id: 'overall', name: 'Overall quality', weight: 100, min: 0, max: 4, levels: GENERIC_LEVELS.map((g, k) => ({ score: k, descriptor: g })) }];
  if (!dims.length) {
    const crit: any[] = Array.isArray(rubric?.criteria) ? rubric.criteria : [];
    const seen = new Set<string>();
    dims = crit.map((c, i) => { let id = slug(String(c.criterion ?? `dimension ${i + 1}`)); while (seen.has(id)) id += '_'; seen.add(id);
      return { id, name: String(c.criterion ?? id), weight: Number(c.weight) || 0, min: 0, max: 4, levels: GENERIC_LEVELS.map((g, k) => ({ score: k, descriptor: k === 4 && c.description ? `${g} - ${c.description}` : g })) }; });
  }
  const high = !!r.highStakes;
  return {
    type: r.type ?? 'ESSAY', dimensions: dims, passPercent: r.passPercent ?? 60, confidenceThreshold: r.confidenceThreshold ?? d.confidenceThreshold, highStakes: high,
    borderlineMargin: r.borderlineMargin ?? 3, samples: r.samples ?? (high ? 2 : 1), sampleRate: r.sampleRate ?? d.sampleRate, prohibitedPatterns: r.prohibitedPatterns ?? [],
    lateRule: r.lateRule ?? {}, unlockOn: r.unlockOn ?? 'SUBMISSION', referenceEvidence: r.referenceEvidence, discloseAnswerGuide: !!r.discloseAnswerGuide,
    minSecondsExpected: r.minSecondsExpected ?? 20, appealWindowDays: r.appealWindowDays ?? d.appealWindowDays, codeTests: r.codeTests,
  };
}

/** Reject patterns that could hang the server (ReDoS) or are invalid; patterns come from admins but run on learner text. */
export function safeRegex(src: string): boolean {
  if (typeof src !== 'string' || !src || src.length > 200) return false;
  if (/(\([^)]*[+*][^)]*\))\s*[+*{]/.test(src) || /\\[1-9]/.test(src) || /(\.\*){3,}/.test(src)) return false;
  try { new RegExp(src, 'i'); return true; } catch { return false; }
}

export function validatePolicy(p: Policy, hasAssignmentCode = false): string[] {
  const out: string[] = [];
  if (!p.dimensions.length) out.push('at least one rubric dimension is required');
  const ids = new Set<string>();
  for (const d of p.dimensions) {
    if (!/^[a-z0-9_]{1,40}$/.test(d.id)) out.push(`dimension id "${d.id}" must be lowercase letters/digits/underscore`);
    if (ids.has(d.id)) out.push(`duplicate dimension id ${d.id}`); ids.add(d.id);
    if (!(d.weight > 0)) out.push(`${d.id}: weight must be > 0`);
    if (!(Number.isFinite(d.min) && Number.isFinite(d.max) && d.min < d.max)) out.push(`${d.id}: scale needs min < max`);
    if (d.levels?.some((l) => l.score < d.min || l.score > d.max)) out.push(`${d.id}: level scores must lie within the scale`);
    if (d.disqualifyBelow !== undefined && (d.disqualifyBelow < d.min || d.disqualifyBelow > d.max)) out.push(`${d.id}: disqualifyBelow outside scale`);
  }
  if (Math.abs(p.dimensions.reduce((s, d) => s + d.weight, 0) - 100) > 0.01) out.push('dimension weights must sum to 100');
  if (!(p.passPercent >= 0 && p.passPercent <= 100)) out.push('passPercent 0..100');
  if (!(p.confidenceThreshold > 0 && p.confidenceThreshold <= 1)) out.push('confidenceThreshold must be in (0,1]');
  if (!Number.isInteger(p.samples) || p.samples < 1 || p.samples > 3) out.push('samples 1..3');
  if (!(p.sampleRate >= 0 && p.sampleRate <= 1)) out.push('sampleRate 0..1');
  if (!UNLOCK_VALUES.includes(p.unlockOn)) out.push(`unlockOn must be one of ${UNLOCK_VALUES.join(',')}`);
  p.prohibitedPatterns.forEach((x) => { if (!safeRegex(x)) out.push(`unsafe or invalid prohibited pattern: ${String(x).slice(0, 40)}`); });
  const l = p.lateRule;
  if (l.dueAt && isNaN(Date.parse(l.dueAt))) out.push('lateRule.dueAt must be an ISO date');
  for (const k of ['graceHours', 'penaltyPercentPerDay', 'maxPenaltyPercent', 'rejectAfterHours'] as const) if (l[k] !== undefined && !(l[k]! >= 0)) out.push(`lateRule.${k} must be >= 0`);
  if ((l.maxPenaltyPercent ?? 0) > 100) out.push('lateRule.maxPenaltyPercent <= 100');
  if (p.codeTests) {
    if (!/^[\w./-]{1,100}$/.test(p.codeTests.entry) || p.codeTests.entry.includes('..')) out.push('codeTests.entry must be a safe relative path');
    if (!p.codeTests.tests?.length || p.codeTests.tests.length > 10) out.push('codeTests needs 1..10 tests');
    if (!(p.codeTests.timeoutMs >= 500 && p.codeTests.timeoutMs <= 30_000)) out.push('codeTests.timeoutMs 500..30000');
    p.codeTests.tests?.forEach((t) => { if (t.dimension && !ids.has(t.dimension)) out.push(`test "${t.name}" targets unknown dimension ${t.dimension}`); });
  } else if (p.type === 'CODE' && !hasAssignmentCode) { /* CODE without tests is allowed: graded by AI + mandatory moderation */ }
  return out;
}

// ---- scoring --------------------------------------------------------------------------------------------------
export interface DimScore { id: string; score: number }
export function computeScore(p: Policy, scores: DimScore[]) {
  const total = p.dimensions.reduce((s, d) => s + d.weight, 0) || 1;
  const by = new Map(scores.map((s) => [s.id, s.score]));
  const per = p.dimensions.map((d) => {
    const raw = by.get(d.id) ?? d.min; const sc = Math.min(d.max, Math.max(d.min, raw));
    return { id: d.id, score: sc, max: d.max, percent: ((sc - d.min) / (d.max - d.min)) * 100, weight: d.weight, disqualified: d.disqualifyBelow !== undefined && sc < d.disqualifyBelow };
  });
  const rawPercent = Math.round(per.reduce((s, x) => s + (x.percent * x.weight) / total, 0) * 100) / 100;
  return { perDimension: per, rawPercent, disqualified: per.filter((x) => x.disqualified).map((x) => x.id) };
}

export function latePenalty(rule: LateRule, submittedAt: Date, extensionHours = 0) {
  if (!rule.dueAt) return { lateHours: 0, penaltyPercent: 0, closed: false };
  const due = new Date(rule.dueAt).getTime() + extensionHours * 3_600_000;
  const lateHours = Math.max(0, (submittedAt.getTime() - due) / 3_600_000);
  const closed = rule.rejectAfterHours !== undefined && lateHours > rule.rejectAfterHours;
  const afterGrace = lateHours - (rule.graceHours ?? 0);
  const penaltyPercent = afterGrace > 0 ? Math.min(rule.maxPenaltyPercent ?? 100, Math.ceil(afterGrace / 24) * (rule.penaltyPercentPerDay ?? 0)) : 0;
  return { lateHours: Math.round(lateHours * 10) / 10, penaltyPercent, closed };
}
export const applyPenalty = (raw: number, penaltyPercent: number) => Math.round(raw * (1 - penaltyPercent / 100) * 100) / 100;

// ---- evidence -------------------------------------------------------------------------------------------------
const norm = (s: string) => s.toLowerCase().replace(/[\u2018\u2019\u201c\u201d"'`]/g, '').replace(/\s+/g, ' ').trim();
export interface Evidence { quote: string; location?: string; verified?: boolean }
/** A quote only counts if it appears verbatim in what the learner submitted (and is long enough to mean something). */
export function verifyEvidence(submission: string, ev: Evidence[]): Evidence[] {
  const hay = norm(submission);
  return ev.map((e) => { const q = norm(e.quote ?? ''); return { ...e, verified: q.length >= 12 && hay.includes(q) }; });
}

export interface AiDim { id: string; score: number; rationale: string; evidence: Evidence[]; confidence: number }
export interface AiOut { dimensions: AiDim[]; overall_feedback: string; overall_confidence: number; flags: string[] }

export function validateAiOutput(p: Policy, o: AiOut): string[] {
  const out: string[] = [];
  const seen = new Map<string, number>(); o.dimensions?.forEach((d) => seen.set(d.id, (seen.get(d.id) ?? 0) + 1));
  for (const d of p.dimensions) {
    if (seen.get(d.id) !== 1) { out.push(`dimension ${d.id} must appear exactly once`); continue; }
    const g = o.dimensions.find((x) => x.id === d.id)!;
    if (!Number.isFinite(g.score) || g.score < d.min || g.score > d.max) out.push(`${d.id}: score ${g.score} outside ${d.min}..${d.max}`);
    else if ((g.score * 2) % 1 !== 0) out.push(`${d.id}: score must be a multiple of 0.5`);
    if (!(g.confidence >= 0 && g.confidence <= 1)) out.push(`${d.id}: confidence must be 0..1`);
    if (!g.rationale?.trim()) out.push(`${d.id}: rationale missing`);
  }
  for (const id of seen.keys()) if (!p.dimensions.some((d) => d.id === id)) out.push(`unknown dimension ${id}`);
  if (!(o.overall_confidence >= 0 && o.overall_confidence <= 1)) out.push('overall_confidence must be 0..1');
  return out;
}

/** Median across self-consistency samples; unstable if any dimension's samples disagree by more than a quarter of its scale. */
export function aggregateSamples(p: Policy, samples: AiOut[]) {
  const med = (xs: number[]) => { const s = [...xs].sort((a, b) => a - b); const m = Math.floor(s.length / 2); return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
  let unstable = false;
  const dims: AiDim[] = p.dimensions.map((d) => {
    const g = samples.map((s) => s.dimensions.find((x) => x.id === d.id)!);
    const scores = g.map((x) => x.score);
    if (Math.max(...scores) - Math.min(...scores) > 0.25 * (d.max - d.min)) unstable = true;
    const pick = g.reduce((best, x) => (Math.abs(x.score - med(scores)) < Math.abs(best.score - med(scores)) ? x : best), g[0]);
    return { id: d.id, score: med(scores), rationale: pick.rationale, evidence: pick.evidence, confidence: Math.min(...g.map((x) => x.confidence)) };
  });
  return { dims, unstable, overallConfidence: Math.min(...samples.map((s) => s.overall_confidence)), feedback: samples[0].overall_feedback, flags: [...new Set(samples.flatMap((s) => s.flags))] };
}

/** Confidence the system is willing to act on: never higher than what is evidenced, stable and fully parsed. */
export function calibrate(o: { modelConfidence: number; evidenceRatio: number; unstable: boolean; unparsed: boolean }): number {
  let c = o.modelConfidence;
  if (o.evidenceRatio < 1) c *= 0.5 + 0.5 * o.evidenceRatio;
  if (o.unstable) c *= 0.6;
  if (o.unparsed) c *= 0.7;
  return Math.round(Math.min(1, Math.max(0, c)) * 1000) / 1000;
}

// ---- moderation routing (ASN-004) -----------------------------------------------------------------------------------
export interface RouteIn {
  p: Policy; confidence: number; rawPercent: number; finalPercent: number; dimScores: DimScore[]; integrityFlags: string[]; unparsed: boolean; testsNotRun: boolean;
  evidenceMissing: string[]; unstable: boolean; invalid: boolean; aiUnavailable: boolean; sampleRoll: number; disqualified: string[];
}
export function routeModeration(i: RouteIn): { reasons: string[]; blocking: boolean; sample: boolean } {
  const r: string[] = [];
  if (i.aiUnavailable) r.push('ai_unavailable');
  if (i.invalid) r.push('ai_invalid_output');
  if (i.confidence < i.p.confidenceThreshold) r.push('low_confidence');
  for (const d of i.p.dimensions) if (d.mandatoryModeration) r.push(`mandatory_dimension:${d.id}`);
  if (i.p.highStakes) r.push('high_stakes');
  i.integrityFlags.forEach((f) => r.push(`integrity:${f}`));
  if (i.unparsed) r.push('unparsed_attachment');
  if (i.testsNotRun) r.push('tests_not_run');
  i.evidenceMissing.forEach((d) => r.push(`evidence_missing:${d}`));
  if (i.unstable) r.push('unstable_scoring');
  if (i.disqualified.length) r.push('disqualifying_dimension');
  if (Math.abs(i.finalPercent - i.p.passPercent) <= i.p.borderlineMargin) r.push('borderline');
  if (i.p.unlockOn === 'MODERATED_SCORE') r.push('moderated_score_required');
  const blocking = r.length > 0;
  return { reasons: r, blocking, sample: !blocking && i.sampleRoll < i.p.sampleRate };
}

// ---- integrity indicators (never convict: they only force human review) ----------------------------------------------
const GRADER_INJECTION = /(give (me |this )?(full|maximum|top|100%?) (marks|score|grade)|award (me )?(full|maximum) (marks|score)|ignore (the )?(rubric|grading|scoring)|you (must|should) (award|give|assign)|score (this|it) (as )?(a )?(10|100|5|4)\b)/i;
export const injectionAttempt = (t: string) => hasInjection(t) || GRADER_INJECTION.test(t);

/** Containment of the smaller text's 5-word shingles in the larger one; needs enough text to be meaningful. */
export function similarity(a: string, b: string): number {
  const A = shingles(a, 5), B = shingles(b, 5);
  if (Math.min(A.size, B.size) < 20) return 0;
  const [s, l] = A.size <= B.size ? [A, B] : [B, A];
  let hit = 0; for (const x of s) if (l.has(x)) hit++;
  return Math.round((hit / s.size) * 1000) / 1000;
}

export function timingFlag(words: number, secondsSinceAvailable: number | null, minSeconds: number): string | null {
  if (secondsSinceAvailable === null) return null;
  if (words > 50 && secondsSinceAvailable < minSeconds) return 'impossible_timing';
  if (words > 200 && words / Math.max(1, secondsSinceAvailable) > 8) return 'impossible_timing';
  return null;
}

export function matchProhibited(text: string, patterns: string[]): string[] {
  const hay = text.slice(0, 200_000);
  return patterns.filter((p) => safeRegex(p) && new RegExp(p, 'i').test(hay));
}

export const wordCount = (t: string) => (t.match(/\S+/g) ?? []).length;
